/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eshan
 */
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.*;
        
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
        setDefaultCloseOperation(IssueBook.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        d1 = new com.toedter.calendar.JDateChooser();
        d2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        issue = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(325, 125, 0, 0));
        setLocation(new java.awt.Point(325, 125));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l1.setText("Book ID");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 30));

        l2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l2.setText("Student ID");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 30));

        l3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l3.setText("Issue Date");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, 30));

        l4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l4.setText("Due Date");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 30));

        t1.setBackground(new java.awt.Color(51, 51, 51));
        t1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 250, 30));

        t2.setBackground(new java.awt.Color(51, 51, 51));
        t2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 250, 30));

        d1.setBackground(new java.awt.Color(51, 51, 51));
        d1.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 250, 30));

        d2.setBackground(new java.awt.Color(51, 51, 51));
        d2.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 250, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Issue Book");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 50));

        issue.setBackground(new java.awt.Color(204, 204, 204));
        issue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issue.setText("Issue");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 80, -1));

        close.setBackground(new java.awt.Color(204, 204, 204));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Catalog-Management.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
        // TODO add your handling code here:
        String url="jdbc:mysql://localhost/library";
        String user="root";
        String pwd="SHA#356#xp123";
        String query="insert into issuebook values (?,?,?,?,?)";
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        String bookid=t1.getText();
        String studentid=t2.getText();
        String issuedate=dFormat.format(d1.getDate());
        String duedate=dFormat.format(d2.getDate());
        String returnbook="no";
        String query1="update books set copies= copies-1 where book_id='"+bookid+"'";
        try
        {
            Connection conn=DriverManager.getConnection(url,user,pwd);
            PreparedStatement stm = conn.prepareCall(query);
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from books where book_id='"+bookid+"'");
            if (rs.next())
            {
                ResultSet rs1=st.executeQuery("select * from student where student_id='"+studentid+"'");
                if (rs1.next())
                {
                    stm.setString(1,bookid);
                    stm.setString(2,studentid);
                    stm.setString(3,issuedate);
                    stm.setString(4,duedate);
                    stm.setString(5,returnbook);
                    stm.execute();
                    JOptionPane.showMessageDialog(null,"Book successfully issued");
                    t1.setText("");
                    st.executeUpdate(query1);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Incorrect Student ID");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Incorrect Book ID");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Connection Error");
        }
    }//GEN-LAST:event_issueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private com.toedter.calendar.JDateChooser d1;
    private com.toedter.calendar.JDateChooser d2;
    private javax.swing.JButton issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
