/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eshan
 */
import java.sql.*;
import javax.swing.*;

public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
        setDefaultCloseOperation(ReturnBook.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        returnb = new javax.swing.JButton();
        close = new javax.swing.JButton();
        search = new javax.swing.JButton();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(325, 125, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Return Book");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 50));

        l1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l1.setText("Book ID");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 90, 30));

        l2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l2.setText("Student ID");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 30));

        t1.setBackground(new java.awt.Color(102, 102, 102));
        t1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 250, 30));

        t2.setBackground(new java.awt.Color(102, 102, 102));
        t2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 250, 30));

        l3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l3.setText("Issue Date");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 110, 30));

        l4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l4.setText("Due Date");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 100, 30));

        returnb.setBackground(new java.awt.Color(204, 204, 204));
        returnb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnb.setText("Return");
        returnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbActionPerformed(evt);
            }
        });
        getContentPane().add(returnb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 80, -1));

        close.setBackground(new java.awt.Color(204, 204, 204));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 80, -1));

        search.setBackground(new java.awt.Color(51, 51, 51));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        d1.setBackground(new java.awt.Color(102, 102, 102));
        d1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 250, 30));

        d2.setBackground(new java.awt.Color(102, 102, 102));
        d2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -240, 490, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbActionPerformed
        // TODO add your handling code here:
        String url="jdbc:mysql://localhost/library";
        String user="root";
        String pwd="SHA#356#xp123";
        String bookid=t1.getText();
        String studentid=t2.getText();
        String query="update issuebook set return_book='yes' where book_id='"+bookid+"'and student_id='"+studentid+"'";
        String query1="update books set copies= copies+1 where book_id='"+bookid+"'";
        try
        {
            Connection conn=DriverManager.getConnection(url,user,pwd);
            Statement st=conn.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Book successfully Returned");
            st.executeUpdate(query1);
            t1.setText("");
            d1.setText("");
            d2.setText("");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Connection Error");
        }
    }//GEN-LAST:event_returnbActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String url="jdbc:mysql://localhost/library";
        String user="root";
        String pwd="SHA#356#xp123";
        String bookid=t1.getText();
        String studentid=t2.getText();
        
        try
        {
            Connection conn=DriverManager.getConnection(url,user,pwd);
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from issuebook where book_id='"+bookid+"'and student_id='"+studentid+"'");
            if (rs.next())
            {
                d1.setText(rs.getString(3));
                d2.setText(rs.getString(4));
                t1.setEditable(false);
                t2.setEditable(false);
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Incorrect Book Id or Student ID");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Connection Error");
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JButton returnb;
    private javax.swing.JButton search;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
